package media

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

// Cookie 是一条从登录浏览器读出的站点 Cookie。
type Cookie struct {
	Domain   string
	Path     string
	Name     string
	Value    string
	Secure   bool
	HttpOnly bool
	// ExpiresAt 为过期时间；零值表示会话 Cookie。
	ExpiresAt time.Time
}

// NetscapeHeader 是 Netscape cookies.txt 的标准文件头。
// yt-dlp 认识该格式，且会读取 "#HttpOnly_" 前缀的行（cookies.py）。
const NetscapeHeader = "# Netscape HTTP Cookie File\n" +
	"# This file is generated by AnyDLNA. Do not edit.\n\n"

// WriteNetscapeCookieFile 把 Cookie 列表写成 yt-dlp 可读的 Netscape 格式文件。
// 关键格式要求（已对照 yt-dlp cookies.py 的解析逻辑）：
//   - 每行 7 个制表符分隔字段，顺序为 domain / includeSubdomains / path /
//     secure / expires / name / value；
//   - HttpOnly Cookie 的域名必须以 "#HttpOnly_" 前缀书写，否则读到的
//     行会被当成注释丢弃；
//   - expires 必须是非负十进制整数，0 表示会话 Cookie；
//   - 值中若含制表符或换行会破坏列结构，转换为空格。
func WriteNetscapeCookieFile(path string, cookies []Cookie) error {
	var sb strings.Builder
	sb.WriteString(NetscapeHeader)
	for _, c := range cookies {
		domain := strings.TrimSpace(c.Domain)
		if domain == "" || c.Name == "" {
			continue
		}
		// 会话 Cookie（无过期时间）写 0，yt-dlp 会将其识别为会话 Cookie。
		expires := int64(0)
		if !c.ExpiresAt.IsZero() {
			expires = c.ExpiresAt.Unix()
			if expires < 0 {
				expires = 0
			}
		}
		field := func(s string) string {
			s = strings.NewReplacer("\t", " ", "\n", " ", "\r", " ").Replace(s)
			return s
		}
		// HttpOnly 前缀加在域名前，与 yt-dlp 的解析约定一致。
		domainField := field(domain)
		if c.HttpOnly {
			domainField = "#HttpOnly_" + domainField
		}
		includeSubdomains := "FALSE"
		if strings.HasPrefix(domain, ".") {
			includeSubdomains = "TRUE"
		}
		secure := "FALSE"
		if c.Secure {
			secure = "TRUE"
		}
		line := strings.Join([]string{
			domainField,
			includeSubdomains,
			field(defaultPath(c.Path)),
			secure,
			strconv.FormatInt(expires, 10),
			field(c.Name),
			field(c.Value),
		}, "\t")
		sb.WriteString(line)
		sb.WriteString("\n")
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("创建 Cookies 目录失败: %w", err)
	}
	// Cookies 含登录凭证，权限限定为当前用户可读写。
	if err := os.WriteFile(path, []byte(sb.String()), 0o600); err != nil {
		return fmt.Errorf("写入 Cookies 文件失败: %w", err)
	}
	return nil
}

// defaultPath 返回 Cookie 路径，为空时按规范默认为根路径。
func defaultPath(path string) string {
	if strings.TrimSpace(path) == "" {
		return "/"
	}
	return path
}

// SortCookies 按域名与名称排序，让导出的文件内容稳定、便于比对。
func SortCookies(cookies []Cookie) {
	sort.Slice(cookies, func(i, j int) bool {
		if cookies[i].Domain != cookies[j].Domain {
			return cookies[i].Domain < cookies[j].Domain
		}
		if cookies[i].Path != cookies[j].Path {
			return cookies[i].Path < cookies[j].Path
		}
		return cookies[i].Name < cookies[j].Name
	})
}

// SaveCookies 把登录浏览器读到的 Cookie 持久化为 yt-dlp 用的文件。
func SaveCookies(cookies []Cookie) (int, error) {
	if len(cookies) == 0 {
		return 0, fmt.Errorf("未读取到任何 Cookie，请确认已在浏览器中完成登录")
	}
	path, err := CookieFilePath()
	if err != nil {
		return 0, err
	}
	SortCookies(cookies)
	if err := WriteNetscapeCookieFile(path, cookies); err != nil {
		return 0, err
	}
	return len(cookies), nil
}

// CookiesInfo 描述已保存的登录浏览器 Cookies 状态，供设置页展示。
type CookiesInfo struct {
	Exists  bool   `json:"exists"`
	Count   int    `json:"count"`
	SavedAt string `json:"savedAt"` // 本地时间字符串，空表示尚未保存
	Path    string `json:"path"`
}

// CookiesStatus 读取已保存的 Cookies 文件状态。
func CookiesStatus() CookiesInfo {
	info := CookiesInfo{}
	path, err := CookieFilePath()
	if err != nil {
		return info
	}
	info.Path = path
	st, err := os.Stat(path)
	if err != nil || st.Size() == 0 {
		return info
	}
	info.Exists = true
	info.SavedAt = st.ModTime().Format("2006-01-02 15:04:05")
	// 统计 Cookie 行数（跳过注释与空行）。
	data, err := os.ReadFile(path)
	if err != nil {
		return info
	}
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") && !strings.HasPrefix(trimmed, "#HttpOnly_") {
			continue
		}
		info.Count++
	}
	return info
}

// DeleteCookies 删除已保存的 Cookies 文件（用于退出登录/清除登录态）。
func DeleteCookies() error {
	path, err := CookieFilePath()
	if err != nil {
		return err
	}
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
