// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDeviceManually(arg1) {
  return window['go']['main']['App']['AddDeviceManually'](arg1);
}

export function Cast(arg1, arg2) {
  return window['go']['main']['App']['Cast'](arg1, arg2);
}

export function CastURL(arg1, arg2) {
  return window['go']['main']['App']['CastURL'](arg1, arg2);
}

export function ClearCookies() {
  return window['go']['main']['App']['ClearCookies']();
}

export function CloseLoginBrowser() {
  return window['go']['main']['App']['CloseLoginBrowser']();
}

export function DeviceCapabilityInfo(arg1) {
  return window['go']['main']['App']['DeviceCapabilityInfo'](arg1);
}

export function GetCastStatus() {
  return window['go']['main']['App']['GetCastStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCookieStatus() {
  return window['go']['main']['App']['GetCookieStatus']();
}

export function GetVolume() {
  return window['go']['main']['App']['GetVolume']();
}

export function LoginBrowserStatus() {
  return window['go']['main']['App']['LoginBrowserStatus']();
}

export function OpenLoginBrowser(arg1) {
  return window['go']['main']['App']['OpenLoginBrowser'](arg1);
}

export function PickVideo(arg1) {
  return window['go']['main']['App']['PickVideo'](arg1);
}

export function PlayPause() {
  return window['go']['main']['App']['PlayPause']();
}

export function Poll() {
  return window['go']['main']['App']['Poll']();
}

export function ResetLoginBrowser() {
  return window['go']['main']['App']['ResetLoginBrowser']();
}

export function ResolveURL(arg1, arg2) {
  return window['go']['main']['App']['ResolveURL'](arg1, arg2);
}

export function SaveBrowserCookies() {
  return window['go']['main']['App']['SaveBrowserCookies']();
}

export function SearchDevices(arg1) {
  return window['go']['main']['App']['SearchDevices'](arg1);
}

export function SeekTo(arg1) {
  return window['go']['main']['App']['SeekTo'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function StopCast() {
  return window['go']['main']['App']['StopCast']();
}

export function SystemProxy() {
  return window['go']['main']['App']['SystemProxy']();
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}
