// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {media} from '../models';

export function AddDeviceManually(arg1:string):Promise<main.DeviceInfo>;

export function Cast(arg1:string,arg2:string):Promise<main.CastStatus>;

export function CastURL(arg1:string,arg2:string):Promise<main.CastStatus>;

export function ClearCookies():Promise<void>;

export function CloseLoginBrowser():Promise<void>;

export function DeviceCapabilityInfo(arg1:string):Promise<main.DeviceFormats>;

export function DiagLogPath():Promise<string>;

export function GetCastStatus():Promise<main.CastStatus>;

export function GetConfig():Promise<media.Config>;

export function GetCookieStatus():Promise<media.CookiesInfo>;

export function GetVolume():Promise<number>;

export function LoginBrowserStatus():Promise<main.LoginBrowserInfo>;

export function OpenLoginBrowser(arg1:string):Promise<void>;

export function PickVideo(arg1:string):Promise<main.PickedVideo>;

export function PlayPause():Promise<void>;

export function Poll():Promise<main.Position>;

export function ResetLoginBrowser():Promise<void>;

export function ResolveURL(arg1:string,arg2:string):Promise<main.ResolvedInfo>;

export function SaveBrowserCookies():Promise<media.CookiesInfo>;

export function SearchDevices(arg1:number):Promise<Array<main.DeviceInfo>>;

export function SeekTo(arg1:number):Promise<void>;

export function SetConfig(arg1:media.Config):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function StopCast():Promise<void>;

export function SystemProxy():Promise<string>;

export function TestProxy(arg1:media.Config):Promise<string>;
