// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDeviceManually(arg1) {
  return window['go']['main']['App']['AddDeviceManually'](arg1);
}

export function Cast(arg1, arg2) {
  return window['go']['main']['App']['Cast'](arg1, arg2);
}

export function CastURL(arg1, arg2) {
  return window['go']['main']['App']['CastURL'](arg1, arg2);
}

export function GetCastStatus() {
  return window['go']['main']['App']['GetCastStatus']();
}

export function GetOptions() {
  return window['go']['main']['App']['GetOptions']();
}

export function GetVolume() {
  return window['go']['main']['App']['GetVolume']();
}

export function PickVideo() {
  return window['go']['main']['App']['PickVideo']();
}

export function PlayPause() {
  return window['go']['main']['App']['PlayPause']();
}

export function Poll() {
  return window['go']['main']['App']['Poll']();
}

export function ResolveURL(arg1) {
  return window['go']['main']['App']['ResolveURL'](arg1);
}

export function SearchDevices(arg1) {
  return window['go']['main']['App']['SearchDevices'](arg1);
}

export function SeekTo(arg1) {
  return window['go']['main']['App']['SeekTo'](arg1);
}

export function SetOptions(arg1, arg2) {
  return window['go']['main']['App']['SetOptions'](arg1, arg2);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function StopCast() {
  return window['go']['main']['App']['StopCast']();
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}
